# Dockerfile
FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npx prisma generate # Gera os arquivos necessários para @prisma/client

RUN npm run build

CMD ["npm", "start"]
